# Generated by Django 2.2.10 on 2021-07-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
