# Generated by Django 2.2.10 on 2021-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0007_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('criteria', models.CharField(max_length=255)),
                ('loop', models.IntegerField()),
                ('success_message', models.TextField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
