# Generated by Django 2.2.10 on 2021-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('example_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_elements',
            field=models.ManyToManyField(to='application.question_element'),
        ),
    ]
