# Generated by Django 2.2.10 on 2021-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210715_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='criteria',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='loop',
            field=models.IntegerField(null=True),
        ),
    ]
