# Generated by Django 2.2.10 on 2021-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210715_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='key',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
