# Generated by Django 2.2.10 on 2021-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210715_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='failure_message',
            field=models.TextField(null=True),
        ),
    ]
