# Generated by Django 2.2.10 on 2021-07-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_exercise_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.topic'),
        ),
    ]
